version: 2.1

jobs:
  docs-deploy:
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            npm install
            git config user.email "morriswchris@gmail.com"
            git config user.name "Chris Morris"
      - add_ssh_keys:
          fingerprints:
            - "73:77:77:37:4d:60:89:cf:4b:7d:cf:e2:91:2a:30:09"
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - docs-deploy:
          filters:
            branches:
              only: master
